name: Python application  

on:
  push:
    branches: [main]      #this is the trigger for push requests
  pull_request:
    branches: [main]      #this is the trigger for pull requests, both on main branch

jobs:
  test:
    runs-on: windows-latest  #running on windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  #check out the repo code in workflow

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  #Specify the Python version (3.12.4 for my computer)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install pytest                   

      - name: Run tests
        run: |
          pytest  
